### ISSUE TITLE
Showing upvote/downvotes in the song list

### ISSUE THREAD

**Issue by swift-kim** [Kylemc1413/BeatSaverVoting#1]
If I remember correctly, before the recent 360 degree mode update, I was able to see 👍/👎 icons for songs I upvoted/downvoted in the song list.

@Kylemc1413, Do you happen to be interested with bringing the feature back in later releases?  (maybe not exactly the same as before because there is less space now)

Thanks!

**Comment by Kylemc1413** [comment]
That's not something this mod is intended to do, that sounds like a feature request better off in SongBrowser or something similar, which used to display that information iirc
