### ISSUE TITLE
Unable to upvote/downvote songs

### ISSUE THREAD

**Issue by tobloef** [Kylemc1413/BeatSaverVoting#3]
I can see the arrows and the score, but they're not clickable, as far as I can tell.

**Comment by tobloef** [comment]
Actually, after some googling it seems like you need to use the steam version for it to work, is that right?

**Comment by Kylemc1413** [comment]
Correct, there is no way to vote on beatsaver using oculus as authentication currently

**Comment by Meivyn** [comment]
I noticed that when you're playing with Steam without SteamVR installed, you HAVE to append the `-vrmode oculus` in the launch options or you won't be able to vote as well. Is this intended behavior?
